/**
 * 支持的编程语言列表
 */
export const SUPPORTED_LANGUAGES = [
  { value: 'javascript', label: 'JavaScript', extension: '.js' },
  { value: 'typescript', label: 'TypeScript', extension: '.ts' },
  { value: 'python', label: 'Python', extension: '.py' },
  { value: 'java', label: 'Java', extension: '.java' },
  { value: 'cpp', label: 'C++', extension: '.cpp' },
  { value: 'c', label: 'C', extension: '.c' },
  { value: 'csharp', label: 'C#', extension: '.cs' },
  { value: 'go', label: 'Go', extension: '.go' },
  { value: 'rust', label: 'Rust', extension: '.rs' },
  { value: 'php', label: 'PHP', extension: '.php' },
  { value: 'ruby', label: 'Ruby', extension: '.rb' },
  { value: 'swift', label: 'Swift', extension: '.swift' },
  { value: 'kotlin', label: 'Kotlin', extension: '.kt' },
  { value: 'scala', label: 'Scala', extension: '.scala' },
  { value: 'html', label: 'HTML', extension: '.html' },
  { value: 'css', label: 'CSS', extension: '.css' },
  { value: 'scss', label: 'SCSS', extension: '.scss' },
  { value: 'less', label: 'Less', extension: '.less' },
  { value: 'json', label: 'JSON', extension: '.json' },
  { value: 'xml', label: 'XML', extension: '.xml' },
  { value: 'yaml', label: 'YAML', extension: '.yaml' },
  { value: 'markdown', label: 'Markdown', extension: '.md' },
  { value: 'sql', label: 'SQL', extension: '.sql' },
  { value: 'shell', label: 'Shell', extension: '.sh' },
  { value: 'dockerfile', label: 'Dockerfile', extension: 'Dockerfile' },
  { value: 'plaintext', label: 'Plain Text', extension: '.txt' },
];